// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpC5P79iOH6cCa3fs4VK-SaHnIoeIPNKg',
    appId: '1:725660898004:web:c1e22bf500a8615ca12141',
    messagingSenderId: '725660898004',
    projectId: 'imagifyai-453d3',
    authDomain: 'imagifyai-453d3.firebaseapp.com',
    storageBucket: 'imagifyai-453d3.firebasestorage.app',
    measurementId: 'G-VF92D225D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkbJ4-l08iZGq1K2tVDHRODISdwIFnlHU',
    appId: '1:725660898004:android:54702659a74d021da12141',
    messagingSenderId: '725660898004',
    projectId: 'imagifyai-453d3',
    storageBucket: 'imagifyai-453d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNdfMIbYYKq-sFSD2ajfHREpmzG5jZS1I',
    appId: '1:725660898004:ios:f7f3c9bd4b8887d7a12141',
    messagingSenderId: '725660898004',
    projectId: 'imagifyai-453d3',
    storageBucket: 'imagifyai-453d3.firebasestorage.app',
    iosBundleId: 'com.imagifyai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNdfMIbYYKq-sFSD2ajfHREpmzG5jZS1I',
    appId: '1:725660898004:ios:f7f3c9bd4b8887d7a12141',
    messagingSenderId: '725660898004',
    projectId: 'imagifyai-453d3',
    storageBucket: 'imagifyai-453d3.firebasestorage.app',
    iosBundleId: 'com.imagifyai.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpC5P79iOH6cCa3fs4VK-SaHnIoeIPNKg',
    appId: '1:725660898004:web:e85d8a1d8c577b7da12141',
    messagingSenderId: '725660898004',
    projectId: 'imagifyai-453d3',
    authDomain: 'imagifyai-453d3.firebaseapp.com',
    storageBucket: 'imagifyai-453d3.firebasestorage.app',
    measurementId: 'G-Y44G9P8PMC',
  );

}